### ISSUE TITLE
Use another config file than the default config.json for this plugin.

### ISSUE THREAD

**Issue by alexnuttinck** [carboneio/carbone-ee-plugin-s3#2]
Hi, 

Is it possible to change the `config.json` file name into another like `config-s3.json` for instance?

We are currently deploying carbone-ee with docker and kubernetes.
This would allow us to add this config file with another mount volume and to not erase the config.json generated with the different environment values we setup for the docker image.

For the moment, I changed it manually in our fork to make it work.

Thanks,

Alexandre

**Comment by steevepay** [comment]
Hi,

I do understand your use case. Would it be good if the config file has a custom name, and you must create an environment variable, such as `CARBONE_S3_CONFIG=custom-name-s3.json`?

**Comment by alexnuttinck** [comment]
@steevepay Yes! It sounds perfect to me.

**Comment by steevepay** [comment]
Hello,

The latest released [v1.1.0](https://github.com/carboneio/carbone-ee-plugin-s3/releases/tag/v1.1.0) supports of two environment variables, `CARBONE_S3_CONFIG` for a custom-named config file and `CARBONE_S3_CONFIG_PATH` for a custom config path.
